# Generated by Django 5.2.1 on 2025-05-19 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_corkscrew_order_glass_order_wine_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corkscrew',
            name='order',
        ),
        migrations.RemoveField(
            model_name='glass',
            name='order',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='order',
        ),
    ]
