# Generated by Django 5.2.1 on 2025-05-23 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_corkscrew_order_remove_glass_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='price',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='price_range',
        ),
        migrations.RenameModel(
            old_name='Goods',
            new_name='TypeOfProduct',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfProduct', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_quantity', models.IntegerField(null=True)),
                ('price_range', models.CharField(choices=[('budget', 'Budget'), ('mid-range', 'Mid Range'), ('premium', 'Premium')], default='budget', max_length=20)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.typeofproduct')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='shop.product'),
        ),
    ]
